server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rmmall_2.0.1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#    password: lhhLHH123321
    password: lhh123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true


mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
    - classpath*:com/**/mapper/*Mapper.xml


servlet:
  multipart:
    # 单个文件大小
    max-file-size:  10MB
    # 设置总上传的文件大小
    max-request-size:  20MB







#druid和redis只是引入还没配置，本项目先搭起来再说